 name: Obtener estado de interfaces en switches Huawei CloudEngine
  hosts: cloudengine
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Ejecutar comandos de estado de interfaces
    # Módulo para enviar comandos a CloudEngine
      community.network.ce_command:
        commands:
          - display interface brief
          - display interface description
      register: ce_int_status

    - name: Mostrar salida en texto (stdout_lines)
      ansible.builtin.debug:
        var: ce_int_status.stdout_lines
